### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yfq512** [a312863063/generators-with-stylegan2#20]
Generating image 0/20 ...
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FusedBiasAct' used by {{node Gs/_Run/Gs/G_mapping/Dense0/FusedBiasAct}}with these attrs: [gain=1.41421354, T=DT_FLOAT, axis=1, grad=0, alpha=0.2, act=3]
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]

         [[Gs/_Run/Gs/G_mapping/Dense0/FusedBiasAct]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 55, in <module>
    main()
  File "main.py", line 52, in main
    generate_images(network_pkl, generate_num)
  File "main.py", line 39, in generate_images
    images = Gs.run(z, None, **Gs_kwargs)  # [minibatch, height, width, channel]
  File "/home/aistudio/generators-with-stylegan2/dnnlib/tflib/network.py", line 442, in run
    mb_out = tf.get_default_session().run(out_expr, dict(zip(in_expr, mb_in)))
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FusedBiasAct' used by node Gs/_Run/Gs/G_mapping/Dense0/FusedBiasAct (defined at <string>:96) with these attrs: [gain=1.41421354, T=DT_FLOAT, axis=1, grad=0, alpha=0.2, act=3]
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]

         [[Gs/_Run/Gs/G_mapping/Dense0/FusedBiasAct]]

Errors may have originated from an input operation.
Input Source operations connected to node Gs/_Run/Gs/G_mapping/Dense0/FusedBiasAct:
 Gs/_Run/Gs/G_mapping/Dense0/Const (defined at /home/aistudio/generators-with-stylegan2/dnnlib/tflib/ops/fused_bias_act.py:105)
 Gs/_Run/Gs/G_mapping/Dense0/MatMul (defined at <string>:46)
 Gs/_Run/Gs/G_mapping/Dense0/mul_1 (defined at <string>:67)

**Comment by cuiwow** [comment]
Hi，I meet the same problem，do you solve it？ Could you share the solution to me？@yfq512
